// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using t1_frame.entityframeworkcore.migrations;

#nullable disable

namespace t1_frame.entityframeworkcore.migrations.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    [Migration("20260208074006_MergedFix4")]
    partial class MergedFix4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("t1_frame.domain.T1ApiAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("api_address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("api_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("api_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("base_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("create_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("create_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("update_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("update_on")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("t1_api_address");
                });

            modelBuilder.Entity("t1_frame.domain.T1ApiBase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("base_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("create_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("create_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sys_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sys_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sys_url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("update_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("update_on")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("t1_api_base");
                });
#pragma warning restore 612, 618
        }
    }
}
